const state={data:null,currentView:'home',draft:null,editingId:null,chartRange:'all',pickerMode:'start'};
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const titleCase=value=>String(value||'').replace(/\b\w/g,c=>c.toUpperCase());
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const localDateKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const prettyDate=value=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));
const monthKey=value=>new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));
function openStore(){return new Promise((resolve,reject)=>{const request=indexedDB.open('clarence-fitness',1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('cache'))db.createObjectStore('cache');if(!db.objectStoreNames.contains('queue'))db.createObjectStore('queue',{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function idbGet(store,key){const db=await openStore();return new Promise((resolve,reject)=>{const request=db.transaction(store).objectStore(store).get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function idbPut(store,value,key){const db=await openStore();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');const request=key===undefined?tx.objectStore(store).put(value):tx.objectStore(store).put(value,key);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error);});}
async function idbDelete(store,key){const db=await openStore();return new Promise((resolve,reject)=>{const request=db.transaction(store,'readwrite').objectStore(store).delete(key);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error);});}
async function idbAll(store){const db=await openStore();return new Promise((resolve,reject)=>{const request=db.transaction(store).objectStore(store).getAll();request.onsuccess=()=>resolve(request.result||[]);request.onerror=()=>reject(request.error);});}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body;}
function base64ToBytes(value){const padding='='.repeat((4-value.length%4)%4);const binary=atob((value+padding).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(binary,c=>c.charCodeAt(0));}
function pushSupported(){return 'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window;}
async function currentPushSubscription(){if(!pushSupported())return null;const registration=await navigator.serviceWorker.ready;return registration.pushManager.getSubscription();}
async function refreshPushUi(){const statusText=$('#push-status-text');const enable=$('#enable-notifications');const test=$('#test-notification');if(!statusText)return;if(!pushSupported()){statusText.textContent='Push is unavailable in this browser. Install the HTTPS site as an iPhone Home Screen app first.';enable.disabled=true;return;}try{const status=state.data?.push||await api('/api/push/status');const subscription=await currentPushSubscription();const enabled=Boolean(subscription&&Notification.permission==='granted');statusText.textContent=enabled?'Notifications are enabled on this device.':Notification.permission==='denied'?'Notifications are blocked in iPhone Settings.':'Enable notifications for workout reminders and progression alerts.';enable.textContent=enabled?'Notifications enabled':'Enable notifications';enable.disabled=enabled;test.disabled=!enabled||!status.configured;$('#workout-reminders').checked=Boolean(status.preferences?.workout_reminders);$('#progression-alerts').checked=status.preferences?.progression_alerts!==false;}catch(error){statusText.textContent=error.message;}}
async function enablePush(){const statusText=$('#notification-status');try{if(!pushSupported())throw new Error('Install the HTTPS Fitness app as a Home Screen app on iPhone first.');if(Notification.permission==='denied')throw new Error('Notifications are blocked. Enable them under iPhone Settings → Notifications → Form.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notification permission was not granted.');const status=state.data?.push||await api('/api/push/status');if(!status.public_key)throw new Error('The Fitness server is not configured for push yet.');const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64ToBytes(status.public_key)});await api('/api/push/subscribe',{method:'POST',body:JSON.stringify({subscription:subscription.toJSON()})});statusText.textContent='Subscription saved. Sending a test notification…';await api('/api/push/test',{method:'POST',body:'{}'});statusText.textContent='Enabled. Check your notification banner.';await refreshPushUi();}catch(error){statusText.textContent=error.message;}}
async function savePushPreferences(){try{const result=await api('/api/push/preferences',{method:'PUT',body:JSON.stringify({workout_reminders:$('#workout-reminders').checked,progression_alerts:$('#progression-alerts').checked})});state.data.push=result;$('#notification-status').textContent='Notification preferences saved.';}catch(error){$('#notification-status').textContent=error.message;}}
function setConnection(status,label){const pill=$('#sync-pill');pill.className=`sync-pill ${status}`;pill.querySelector('span').textContent=label;}
async function flushQueue(){for(const item of await idbAll('queue')){await api(item.path||'/api/sessions',{method:item.method||'POST',headers:{'Idempotency-Key':item.id},body:JSON.stringify(item.payload)});await idbDelete('queue',item.id);}}
async function loadData(){try{await flushQueue();state.data=await api('/api/bootstrap');await idbPut('cache',state.data,'bootstrap');setConnection('online','Live');}catch(error){state.data=await idbGet('cache','bootstrap');if(!state.data)throw error;const queued=(await idbAll('queue')).length;setConnection('offline',queued?`${queued} queued`:'Offline');}renderAll();refreshPushUi();}
function loadValue(item){const value=item.added_weight_lb??item.weight_lb??item.actual_weight_lb??item.target_weight_lb;return value===null||value===undefined?'Bodyweight':`${item.added_weight_lb!==null&&item.added_weight_lb!==undefined?'+':''}${Number(value).toLocaleString()} lb`;}
function prescription(item){return `${item.sets??item.target_sets??item.actual_sets??'—'} × ${item.reps??item.target_reps??item.actual_reps??'—'}`;}
function workoutByDay(dayType){return(state.data.programmed_workouts||[]).find(workout=>workout.day_type===dayType);}
function slotById(slotId){return(state.data.exercise_slots||[]).find(slot=>slot.slot_id===slotId);}
function slotLoad(slot){const value=slot.added_weight_lb??slot.weight_lb??slot.current_target_lb;return value===null||value===undefined?'Bodyweight':`${slot.added_weight_lb!==null&&slot.added_weight_lb!==undefined?'+':''}${value} lb`;}
function rotationRule(draft){if(draft.session_kind!=='custom')return`Completes ${draft.rotation_day} and advances to the following rotation day.`;if(draft.advance_rotation)return`Custom session replacing ${draft.rotation_day}; rotation advances after save.`;return'Custom session; selected lift progressions update without advancing the main rotation.';}

function renderHome(){
  const workout=state.data.next_workout;$('#next-day').textContent=workout?.day_type||'No workout';$('#phase-label').textContent=workout?`Phase ${workout.phase||state.data.summary.active_phase} · ${workout.goal_lifts.length} movements`:'No rotation queued';
  $('#next-lifts').innerHTML=(workout?.goal_lifts||[]).map(lift=>`<article class="next-lift"><div class="lift-name">${escapeHtml(lift.exercise)}</div><div><div class="lift-load">${loadValue(lift)}</div><div class="lift-scheme">${prescription(lift)} reps</div></div>${lift.note?`<div class="lift-note">${escapeHtml(lift.note)}</div>`:''}</article>`).join('')||'<div class="empty">No workout queued.</div>';
  const groups=[['Squat','SQ',item=>item.exercise.includes('squat')],['Bench','BP',item=>item.exercise.includes('bench')],['Deadlift','DL',item=>item.exercise.includes('deadlift')],['Press','PR',item=>item.exercise.includes('strict press')||item.exercise==='shoulder press']];
  $('#strength-strip').innerHTML=groups.map(([name,icon,test])=>{const matches=state.data.maxes.filter(test);const best=matches.sort((a,b)=>b.best_load_lb-a.best_load_lb)[0];return`<article class="strength-card"><div class="strength-icon">${icon}</div><strong>${best?`${best.best_load_lb} lb`:'—'}</strong><span>${name} · best completed</span></article>`;}).join('');
  $('#recent-sessions').innerHTML=(state.data.recent_sessions||[]).slice(0,3).map(renderSessionCard).join('')||'<div class="empty">No sessions yet.</div>';
}
function renderSessionCard(session){const chips=(session.attempts||[]).slice(0,4).map(a=>`<span class="lift-chip">${escapeHtml(a.exercise)} · ${loadValue(a)}</span>`).join('');const setCount=(session.attempts||[]).reduce((sum,a)=>sum+(a.sets?.filter(s=>s.status==='complete').length||a.actual_sets||0),0);return`<button class="session-card" data-session-id="${session.id}"><div class="session-top"><div><h3>${escapeHtml(session.day_type)}</h3><div class="session-date">${prettyDate(session.date_logged)} · Phase ${session.phase||'—'}</div></div><span class="status ${session.status}">${session.status}</span></div><div class="session-lifts">${chips}</div><div class="session-summary">${session.attempt_count||session.attempts?.length||0} movements · ${setCount} completed sets</div></button>`;}
function filteredSessions(){const query=$('#history-search')?.value.trim().toLowerCase()||'';const day=$('#history-day')?.value||'';const status=$('#history-status')?.value||'';return(state.data.recent_sessions||[]).filter(s=>(!day||s.day_type===day)&&(!status||s.status===status)&&(!query||s.notes?.toLowerCase().includes(query)||s.attempts.some(a=>a.exercise.toLowerCase().includes(query))));}
function renderHistory(){const sessions=filteredSessions();$('#history-count').textContent=`${sessions.length} of ${state.data.summary.session_count} sessions`;const months=new Map();for(const session of sessions){const key=monthKey(session.date_logged);if(!months.has(key))months.set(key,[]);months.get(key).push(session);}$('#history-list').innerHTML=[...months].map(([month,items])=>`<section class="month-group"><h2 class="month-label">${month}</h2><div class="session-list">${items.map(renderSessionCard).join('')}</div></section>`).join('')||'<div class="empty">No sessions match these filters.</div>';bindSessionCards();}
function bindSessionCards(){$$('[data-session-id]').forEach(button=>button.onclick=()=>openSession(button.dataset.sessionId));}
function openSession(id){const session=state.data.recent_sessions.find(item=>item.id===id);if(!session)return;$('#session-detail').innerHTML=`<div class="modal-head"><div><span class="kicker">${escapeHtml(session.day_type)} · ${prettyDate(session.date_logged)}</span><h2>Session detail</h2></div><button class="icon-button" data-close-dialog>×</button></div><span class="status ${session.status}">${session.status}</span>${session.attempts.map(attempt=>`<section class="review-exercise"><h3>${titleCase(attempt.exercise)}</h3><p class="subtle">${loadValue(attempt)} · target ${prescription(attempt)}</p>${(attempt.sets||[]).map(set=>`<div class="detail-set"><b>#${set.set_number}</b><span>${set.actual_weight_lb??'—'} lb</span><span>${set.actual_reps??'—'} reps</span><span class="status ${set.status}">${set.status}</span></div>`).join('')||'<p class="subtle">Aggregate legacy record</p>'}</section>`).join('')}${session.notes?`<p class="subtle">${escapeHtml(session.notes)}</p>`:''}<div class="modal-actions"><button class="button secondary" data-close-dialog>Close</button><button class="button primary" data-edit-session="${session.id}">Edit session</button></div>`;const dialog=$('#session-dialog');dialog.showModal();$$('[data-close-dialog]').forEach(b=>b.onclick=()=>dialog.close());$('[data-edit-session]').onclick=()=>{dialog.close();populateWorkoutFromSession(session);showView('workout');};}

function renderProgress(){
  $('#maxes-grid').innerHTML=state.data.maxes.map(item=>`<article class="max-card"><span class="kicker">${escapeHtml(item.display_name)}</span><strong>${item.uses_added_weight?'+':''}${item.best_load_lb} lb</strong><span>Best completed · ${prettyDate(item.date_logged)}</span><div class="metric-row"><div><b>${item.estimated_1rm_lb} lb</b><small>Est. 1RM</small></div><div><b>${item.current_target_lb??'—'}${item.current_target_lb?' lb':''}</b><small>Next target</small></div></div></article>`).join('');
  const exercises=[...new Set(state.data.exercise_history.map(p=>p.exercise))].sort();const select=$('#chart-exercise');const current=select.value;select.innerHTML=exercises.map(e=>`<option value="${escapeHtml(e)}">${titleCase(e)}</option>`).join('');if(exercises.includes(current))select.value=current;else if(exercises.length)select.value=exercises.at(-1);renderChart();
}
function chartPoints(){let points=state.data.exercise_history.filter(p=>p.exercise===$('#chart-exercise').value&&p.weight_lb!==null);if(state.chartRange!=='all'){const cutoff=new Date();cutoff.setDate(cutoff.getDate()-Number(state.chartRange));points=points.filter(p=>new Date(`${p.date_logged}T12:00:00`)>=cutoff);}return points;}
function renderChart(){const svg=$('#progress-chart');const exercise=$('#chart-exercise').value;const points=chartPoints();if(!points.length){svg.innerHTML='<text x="360" y="180" text-anchor="middle" class="chart-label">No performance data</text>';$('#chart-summary').innerHTML='';$('#lift-history').innerHTML='';return;}const values=points.map(p=>Number(p.weight_lb));const min=Math.min(...values),max=Math.max(...values),span=Math.max(10,max-min);const W=720,H=360,pad={l:64,r:24,t:28,b:44};const x=i=>pad.l+(i/Math.max(1,points.length-1))*(W-pad.l-pad.r);const y=v=>pad.t+(1-(v-(min-span*.15))/(span*1.3))*(H-pad.t-pad.b);const grid=[0,.25,.5,.75,1].map(step=>{const gy=pad.t+step*(H-pad.t-pad.b);const label=Math.round((max+span*.15)-step*span*1.3);return`<line x1="${pad.l}" y1="${gy}" x2="${W-pad.r}" y2="${gy}" class="chart-grid"/><text x="${pad.l-12}" y="${gy+6}" text-anchor="end" class="chart-label">${label}</text>`;}).join('');const line=points.map((p,i)=>`${i?'L':'M'} ${x(i)} ${y(Number(p.weight_lb))}`).join(' ');const dots=points.map((p,i)=>`<circle cx="${x(i)}" cy="${y(Number(p.weight_lb))}" r="7" class="chart-dot ${p.outcome}"/>`).join('');svg.innerHTML=`${grid}<path d="${line}" class="chart-line"/>${dots}<text x="${pad.l}" y="${H-12}" class="chart-label">${points[0].date_logged.slice(5)}</text><text x="${W-pad.r}" y="${H-12}" text-anchor="end" class="chart-label">${points.at(-1).date_logged.slice(5)}</text>`;const delta=values.at(-1)-values[0];$('#chart-summary').innerHTML=`<span>${titleCase(exercise)}</span><strong>${values.at(-1)} lb · ${delta>=0?'+':''}${delta} lb</strong>`;$('#lift-history').innerHTML=points.slice(-6).reverse().map(p=>`<article class="session-card"><div class="session-top"><div><h3>${prettyDate(p.date_logged)}</h3><div class="session-date">${p.day_type} · ${p.sets||'—'} × ${p.reps||'—'}</div></div><strong>${p.added_weight_lb!==null?'+':''}${p.weight_lb} lb</strong></div></article>`).join('');}
function renderMore(){const s=state.data.summary;$('#system-stats').innerHTML=[['Sessions',s.session_count],['Lift records',s.attempt_count],['Individual sets',s.set_count]].map(([label,value])=>`<article class="panel stat-card"><strong>${value}</strong><span>${label}</span></article>`).join('');$('#program-name').textContent=state.data.program?.name||`Phase ${s.active_phase}`;$('#program-rule').textContent=state.data.program?.progression_rule||'Progression is calculated from verified completed work.';refreshPushUi();}

function pickerHeader(title,kicker='SELECT WORKOUT'){return`<div class="modal-head"><div><span class="kicker">${kicker}</span><h2>${title}</h2></div><button class="icon-button" data-close-picker>×</button></div>`;}
function bindPickerClose(){const dialog=$('#workout-picker-dialog');$$('[data-close-picker]').forEach(button=>button.onclick=()=>dialog.close());}
function renderWorkoutChoices(){
  const nextDay=state.data.next_workout?.day_type;
  const cards=(state.data.programmed_workouts||[]).map(workout=>`<article class="day-choice ${workout.day_type===nextDay?'recommended':''}"><div class="day-choice-head"><div><small>${workout.day_type===nextDay?'Recommended next':'Programmed day'}</small><h3>${workout.day_type}</h3></div><span class="status complete">${workout.goal_lifts.length} lifts</span></div><div class="day-choice-lifts">${workout.goal_lifts.map(lift=>`<div class="day-choice-lift"><span>${titleCase(lift.exercise)}</span><b>${loadValue(lift)} · ${prescription(lift)}</b></div>`).join('')}</div><button class="button ${workout.day_type===nextDay?'primary':'secondary'}" data-start-day="${workout.day_type}">Start ${workout.day_type}</button></article>`).join('');
  $('#workout-picker-content').innerHTML=`${pickerHeader('Choose a workout')}<p class="subtle picker-intro">Follow any programmed day at its current progression targets, or assemble a custom session from individual program slots.</p><div class="day-choice-grid">${cards}</div><article class="custom-entry"><div><h3>Custom workout</h3><p>Mix progression-specific exercises from any day. The main rotation stays unchanged unless you mark the workout as replacing a day.</p></div><button class="button secondary" id="build-custom-workout">Build custom</button></article>`;
  bindPickerClose();$$('[data-start-day]').forEach(button=>button.onclick=()=>startProgrammedWorkout(button.dataset.startDay));$('#build-custom-workout').onclick=()=>renderCustomBuilder(false);
}
function slotOption(slot,{checked=false,disabled=false}={}){const last=slot.last_performance;const lastLoad=last?.weight_lb===null||last?.weight_lb===undefined?'Bodyweight':`${slot.added_weight_lb!==null?'+':''}${last.weight_lb} lb`;return`<label class="slot-option ${disabled?'existing':''}"><input type="checkbox" value="${escapeHtml(slot.slot_id)}" ${checked?'checked':''} ${disabled?'disabled':''}><div><div class="slot-name"><strong>${titleCase(slot.exercise)}</strong><b>${slotLoad(slot)} · ${slot.sets} × ${slot.reps}</b></div>${disabled?'<span class="slot-state">Already added</span>':''}<div class="slot-metrics"><div><small>Last result</small><span>${last?`${last.outcome} · ${lastLoad}`:'No history'}</span></div><div><small>Best complete</small><span>${slot.best_completed_lb===null?'—':`${slot.added_weight_lb!==null?'+':''}${slot.best_completed_lb} lb`}</span></div><div><small>After success</small><span>${slot.next_success_target_lb===null?'—':`${slot.added_weight_lb!==null?'+':''}${slot.next_success_target_lb} lb`}</span></div></div></div></label>`;}
function renderCustomBuilder(append=false){
  state.pickerMode=append?'append':'custom';const existing=new Set(append?(state.draft?.exercises||[]).map(item=>item.slotId).filter(Boolean):[]);const groups=(state.data.programmed_workouts||[]).map(workout=>{const slots=(state.data.exercise_slots||[]).filter(slot=>slot.day_type===workout.day_type);return`<section class="slot-group"><h3>${workout.day_type}</h3><div class="slot-grid">${slots.map(slot=>slotOption(slot,{checked:existing.has(slot.slot_id),disabled:append&&existing.has(slot.slot_id)})).join('')}</div></section>`;}).join('');
  const rotationControl=append?'':`<label>Rotation behavior<select id="custom-rotation"><option value="none">Do not advance rotation</option><option value="Day 1">Replace / complete Day 1</option><option value="Day 2">Replace / complete Day 2</option><option value="Day 3">Replace / complete Day 3</option></select></label>`;
  $('#workout-picker-content').innerHTML=`${pickerHeader(append?'Add program exercises':'Build a custom workout','CUSTOM SESSION')}<p class="subtle picker-intro">Each exercise keeps its own progression slot, target, and history even when combined with exercises from another day.</p><div class="slot-builder-toolbar ${append?'append-mode':''}">${rotationControl}<button class="button secondary" id="add-manual-exercise">Add manual exercise</button></div><div class="slot-groups">${groups}</div><div class="picker-footer"><span class="subtle" id="slot-selection-count">0 exercises selected</span><div><button class="button secondary" id="picker-back">${append?'Cancel':'Back'}</button> <button class="button primary" id="confirm-custom-workout">${append?'Add selected':'Start custom workout'}</button></div></div>`;
  bindPickerClose();const selectable=()=>$$('.slot-option input:checked:not(:disabled)');const updateCount=()=>{$('#slot-selection-count').textContent=`${selectable().length} exercises selected`;};$$('.slot-option input:not(:disabled)').forEach(input=>input.onchange=updateCount);updateCount();$('#picker-back').onclick=()=>append?$('#workout-picker-dialog').close():renderWorkoutChoices();$('#add-manual-exercise').onclick=()=>{if(append){readWorkoutDom();state.draft.exercises.push(newExercise());renderWorkout();saveDraft();$('#workout-picker-dialog').close();}else{createDraft({exercises:[newExercise()]});$('#workout-picker-dialog').close();}};$('#confirm-custom-workout').onclick=()=>{const selected=selectable().map(input=>slotById(input.value)).filter(Boolean);if(!selected.length){$('#slot-selection-count').textContent='Select at least one exercise.';return;}if(append){readWorkoutDom();state.draft.exercises.push(...selected.map(newExercise));renderWorkout();saveDraft();}else{const rotationDay=$('#custom-rotation').value;createDraft({dayType:'Custom',sessionKind:'custom',rotationDay:rotationDay==='none'?null:rotationDay,advanceRotation:rotationDay!=='none',exercises:selected.map(newExercise)});}$('#workout-picker-dialog').close();};
}
function openWorkoutPicker(mode='start'){state.pickerMode=mode;if(mode==='append')renderCustomBuilder(true);else renderWorkoutChoices();$('#workout-picker-dialog').showModal();}

function newExercise(lift={}){const usesAdded=lift.added_weight_lb!==null&&lift.added_weight_lb!==undefined;const count=Number(lift.sets??lift.target_sets??lift.actual_sets??1);return{slotId:lift.slot_id||'',sourceDay:lift.day_type||'',exercise:lift.exercise||'',usesAdded,targetWeight:lift.added_weight_lb??lift.weight_lb??lift.target_weight_lb??'',targetReps:lift.reps??lift.target_reps??lift.actual_reps??'',bestCompleted:lift.best_completed_lb??'',lastOutcome:lift.last_performance?.outcome||'',nextSuccessTarget:lift.next_success_target_lb??'',notes:lift.notes||lift.note||'',sets:Array.from({length:Math.max(1,count)},(_,i)=>({weight:lift.added_weight_lb??lift.weight_lb??lift.actual_weight_lb??lift.target_weight_lb??'',reps:Array.isArray(lift.rep_sequence)?lift.rep_sequence[i]??'':lift.reps??lift.actual_reps??lift.target_reps??'',status:lift.outcome||'complete',rpe:'',rir:''}))};}
function exerciseFromAttempt(attempt){const slot=(state.data?.exercise_slots||[]).find(item=>item.canonical_exercise===attempt.canonical_exercise);return{slotId:slot?.slot_id||'',sourceDay:slot?.day_type||'',exercise:attempt.exercise,usesAdded:attempt.added_weight_lb!==null,targetWeight:attempt.added_weight_lb??attempt.target_weight_lb??attempt.actual_weight_lb??'',targetReps:attempt.target_reps??attempt.actual_reps??'',bestCompleted:slot?.best_completed_lb??'',lastOutcome:slot?.last_performance?.outcome||'',nextSuccessTarget:slot?.next_success_target_lb??'',notes:attempt.notes||'',sets:(attempt.sets?.length?attempt.sets:Array.from({length:attempt.actual_sets||attempt.target_sets||1},(_,i)=>({set_number:i+1,actual_weight_lb:attempt.actual_weight_lb??attempt.added_weight_lb,actual_reps:attempt.rep_sequence?.[i]??attempt.actual_reps,status:attempt.outcome}))).map(set=>({weight:set.actual_weight_lb??'',reps:set.actual_reps??'',status:set.status||attempt.outcome,rpe:set.rpe??'',rir:set.rir??''}))};}
function createDraft({dayType='Custom',sessionKind='custom',rotationDay=null,advanceRotation=false,exercises=[]}){state.editingId=null;state.draft={date_logged:localDateKey(),day_type:dayType,session_kind:sessionKind,rotation_day:rotationDay,advance_rotation:advanceRotation,notes:'',exercises};saveDraft();renderWorkout();showView('workout');}
function startProgrammedWorkout(dayType){const workout=workoutByDay(dayType);if(!workout)return;createDraft({dayType,sessionKind:'programmed',rotationDay:dayType,advanceRotation:true,exercises:workout.goal_lifts.map(lift=>{const slot=(state.data.exercise_slots||[]).find(item=>item.day_type===dayType&&item.canonical_exercise===lift.exercise);return newExercise(slot||{...lift,day_type:dayType});})});$('#workout-picker-dialog').close();}
function startWorkout(){if(state.draft){renderWorkout();showView('workout');return;}openWorkoutPicker('start');}
async function restoreDraft(){state.draft=await idbGet('cache','workout-draft');if(state.draft)renderWorkout();}
async function saveDraft(){if(state.draft){state.draft.updated_at=new Date().toISOString();await idbPut('cache',state.draft,'workout-draft');$('#draft-status').textContent=`Draft saved · ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`;}}
function readWorkoutDom(){if(!state.draft)return;state.draft.date_logged=$('#workout-date').value;state.draft.notes=$('#session-notes').value;state.draft.exercises=$$('.exercise-editor').map(editor=>({slotId:editor.dataset.slotId||'',sourceDay:editor.dataset.sourceDay||'',exercise:editor.querySelector('[data-exercise]').value.trim(),usesAdded:editor.dataset.added==='true',targetWeight:editor.dataset.targetWeight,targetReps:editor.dataset.targetReps,bestCompleted:editor.dataset.bestCompleted||'',lastOutcome:editor.dataset.lastOutcome||'',nextSuccessTarget:editor.dataset.nextSuccessTarget||'',notes:editor.querySelector('[data-exercise-notes]').value,sets:[...editor.querySelectorAll('.set-row')].map(row=>({weight:row.querySelector('[data-weight]').value,reps:row.querySelector('[data-reps]').value,status:row.dataset.status,rpe:row.querySelector('[data-rpe]').value,rir:row.querySelector('[data-rir]').value}))}));saveDraft();}
function setRow(set,index){return`<div class="set-row" data-status="${set.status||'complete'}"><button type="button" class="mini-button muted set-number">#${index+1}</button><input data-weight inputmode="decimal" type="number" step=".5" value="${escapeHtml(set.weight)}" aria-label="Weight"><input data-reps inputmode="numeric" type="number" min="0" value="${escapeHtml(set.reps)}" aria-label="Reps"><button type="button" class="set-toggle ${set.status||'complete'}" aria-label="Set status">✓</button><div class="set-advanced"><label>RPE<input data-rpe inputmode="decimal" type="number" min="1" max="10" step=".5" value="${escapeHtml(set.rpe)}"></label><label>RIR<input data-rir inputmode="numeric" type="number" min="0" max="10" value="${escapeHtml(set.rir)}"></label></div></div>`;}
function exerciseEditor(exercise,index){const context=[exercise.sourceDay?`Slot · ${exercise.sourceDay}`:'Manual exercise',exercise.bestCompleted!==''?`Best · ${exercise.usesAdded?'+':''}${exercise.bestCompleted} lb`:null,exercise.lastOutcome?`Last · ${exercise.lastOutcome}`:null,exercise.nextSuccessTarget!==''?`Next after success · ${exercise.usesAdded?'+':''}${exercise.nextSuccessTarget} lb`:null].filter(Boolean);return`<article class="exercise-editor" data-index="${index}" data-slot-id="${escapeHtml(exercise.slotId)}" data-source-day="${escapeHtml(exercise.sourceDay)}" data-added="${exercise.usesAdded}" data-target-weight="${escapeHtml(exercise.targetWeight)}" data-target-reps="${escapeHtml(exercise.targetReps)}" data-best-completed="${escapeHtml(exercise.bestCompleted)}" data-last-outcome="${escapeHtml(exercise.lastOutcome)}" data-next-success-target="${escapeHtml(exercise.nextSuccessTarget)}"><header class="exercise-head"><div class="exercise-title"><input data-exercise value="${escapeHtml(exercise.exercise)}" placeholder="Exercise name"><div class="exercise-prescription">Target · ${exercise.targetWeight||'BW'} lb · ${exercise.sets.length} × ${exercise.targetReps||'—'}</div><div class="exercise-context">${context.map(item=>`<span>${escapeHtml(item)}</span>`).join('')}</div></div><button type="button" class="icon-button remove-exercise">×</button></header><div class="set-table"><div class="set-header"><span>Set</span><span>${exercise.usesAdded?'Added':'Weight'}</span><span>Reps</span><span>Done</span></div>${exercise.sets.map(setRow).join('')}</div><div class="exercise-actions"><button type="button" class="mini-button add-set">＋ Add set</button><button type="button" class="mini-button muted toggle-notes">Details</button></div><label class="notes-field exercise-notes" hidden>Exercise notes<textarea data-exercise-notes rows="2">${escapeHtml(exercise.notes)}</textarea></label></article>`;}
function renderWorkout(){if(!state.draft)return;$('#workout-heading').textContent=state.editingId?'Edit session':state.draft.day_type;$('#workout-date').value=state.draft.date_logged;$('#session-selection-name').textContent=state.draft.session_kind==='custom'?(state.draft.advance_rotation?`Custom · replaces ${state.draft.rotation_day}`:'Custom workout'):state.draft.day_type;$('#session-selection-rule').textContent=rotationRule(state.draft);$('#session-notes').value=state.draft.notes||'';$('#exercise-editors').innerHTML=state.draft.exercises.map(exerciseEditor).join('');bindWorkoutEvents();}
function bindWorkoutEvents(){
  $$('.set-toggle').forEach(button=>button.onclick=()=>{const row=button.closest('.set-row');const states=['complete','partial','missed','skipped'];const next=states[(states.indexOf(row.dataset.status)+1)%states.length];row.dataset.status=next;button.className=`set-toggle ${next}`;button.textContent=next==='complete'?'✓':next==='partial'?'~':next==='missed'?'!':'–';readWorkoutDom();});
  $$('.set-number').forEach(button=>button.onclick=()=>button.closest('.set-row').classList.toggle('expanded'));
  $$('.add-set').forEach(button=>button.onclick=()=>{readWorkoutDom();const index=Number(button.closest('.exercise-editor').dataset.index);const previous=state.draft.exercises[index].sets.at(-1)||{weight:'',reps:'',status:'complete',rpe:'',rir:''};state.draft.exercises[index].sets.push({...previous});renderWorkout();saveDraft();});
  $$('.remove-exercise').forEach(button=>button.onclick=()=>{readWorkoutDom();state.draft.exercises.splice(Number(button.closest('.exercise-editor').dataset.index),1);renderWorkout();saveDraft();});
  $$('.toggle-notes').forEach(button=>button.onclick=()=>{const field=button.closest('.exercise-editor').querySelector('.exercise-notes');field.hidden=!field.hidden;});
  $$('#workout-form input,#workout-form select,#workout-form textarea').forEach(input=>input.onchange=readWorkoutDom);
}
function payloadFromDraft(){readWorkoutDom();return{date_logged:state.draft.date_logged,day_type:state.draft.day_type,session_kind:state.draft.session_kind||'programmed',rotation_day:state.draft.rotation_day||null,advance_rotation:Boolean(state.draft.advance_rotation),phase:state.data.summary.active_phase,notes:state.draft.notes,source:'pwa-v5',attempts:state.draft.exercises.filter(e=>e.exercise).map(exercise=>{const statuses=exercise.sets.map(s=>s.status);const outcome=statuses.every(s=>s==='complete')?'complete':statuses.every(s=>s==='skipped')?'skipped':statuses.includes('missed')?'missed':'partial';const load=Number(exercise.targetWeight);return{exercise:exercise.exercise,outcome,target_weight_lb:exercise.usesAdded?null:load,target_added_weight_lb:exercise.usesAdded?load:null,added_weight_lb:exercise.usesAdded?load:null,target_sets:exercise.sets.length,target_reps:Number(exercise.targetReps),notes:exercise.notes,sets_detail:exercise.sets.map(set=>({target_weight_lb:Number(exercise.targetWeight),actual_weight_lb:set.weight===''?null:Number(set.weight),target_reps:Number(exercise.targetReps),actual_reps:set.reps===''?null:Number(set.reps),status:set.status,rpe:set.rpe===''?null:Number(set.rpe),rir:set.rir===''?null:Number(set.rir)}))};})};}
function reviewWorkout(){const payload=payloadFromDraft();if(!payload.attempts.length){$('#form-status').textContent='Add at least one exercise.';return;}$('#review-content').innerHTML=`<p class="subtle">${prettyDate(payload.date_logged)} · ${escapeHtml(payload.day_type)}</p>${payload.attempts.map(a=>`<section class="review-exercise"><h3>${titleCase(a.exercise)}</h3><p class="subtle">${a.sets_detail.length} sets · ${a.outcome}</p>${a.sets_detail.map((s,i)=>`<div class="detail-set"><b>#${i+1}</b><span>${s.actual_weight_lb??'—'} lb</span><span>${s.actual_reps??'—'} reps</span><span class="status ${s.status}">${s.status}</span></div>`).join('')}</section>`).join('')}`;$('#review-dialog').showModal();}
async function saveWorkout(){const payload=payloadFromDraft();const id=uid();const method=state.editingId?'PUT':'POST';const path=state.editingId?`/api/sessions/${encodeURIComponent(state.editingId)}`:'/api/sessions';try{const result=await api(path,{method,headers:{'Idempotency-Key':id},body:JSON.stringify(payload)});const verified=await api(`/api/sessions/${encodeURIComponent(result.session.id)}`);if(!verified.session)throw new Error('Saved session could not be verified.');await idbDelete('cache','workout-draft');state.draft=null;state.editingId=null;$('#review-dialog').close();await loadData();showView('home');}catch(error){await idbPut('queue',{id,path,payload,method,created_at:new Date().toISOString()});$('#review-dialog').close();$('#form-status').textContent='Mac mini unavailable. This workout is queued safely on this device.';setConnection('offline','1 queued');}}
function populateWorkoutFromSession(session){state.editingId=session.id;state.draft={date_logged:session.date_logged,day_type:session.day_type,session_kind:session.session_kind||(session.day_type==='Custom'?'custom':'programmed'),rotation_day:session.rotation_day||(session.day_type!=='Custom'?session.day_type:null),advance_rotation:Boolean(session.advances_rotation),notes:session.notes||'',exercises:session.attempts.map(exerciseFromAttempt)};renderWorkout();saveDraft();}
function showView(view){state.currentView=view;$$('.view').forEach(el=>el.classList.toggle('active',el.id===view));$$('.nav-button').forEach(el=>el.classList.toggle('active',el.dataset.viewTarget===view));if(view==='workout'&&!state.draft)startWorkout();if(view==='history')renderHistory();if(view==='progress')renderProgress();window.scrollTo({top:0,behavior:'smooth'});}
function renderAll(){renderHome();renderHistory();renderProgress();renderMore();bindSessionCards();if(state.draft)renderWorkout();}

$$('[data-view-target]').forEach(button=>button.onclick=()=>showView(button.dataset.viewTarget));
$('#start-workout').onclick=()=>startWorkout();$('#add-exercise').onclick=()=>openWorkoutPicker('append');$('#change-workout').onclick=()=>openWorkoutPicker('start');
$('#discard-workout').onclick=async()=>{if(confirm('Discard this workout draft?')){state.draft=null;state.editingId=null;await idbDelete('cache','workout-draft');showView('home');}};
$('#workout-form').onsubmit=event=>{event.preventDefault();reviewWorkout();};$('#confirm-save').onclick=event=>{event.preventDefault();saveWorkout();};
$('#history-search').oninput=renderHistory;$('#history-day').onchange=renderHistory;$('#history-status').onchange=renderHistory;
$('#chart-exercise').onchange=renderChart;$$('[data-range]').forEach(button=>button.onclick=()=>{$$('[data-range]').forEach(b=>b.classList.remove('active'));button.classList.add('active');state.chartRange=button.dataset.range;renderChart();});
$('#refresh-data').onclick=loadData;window.addEventListener('online',loadData);window.addEventListener('offline',()=>setConnection('offline','Offline'));
$('#enable-notifications').onclick=enablePush;$('#test-notification').onclick=async()=>{try{await api('/api/push/test',{method:'POST',body:'{}'});$('#notification-status').textContent='Test notification sent.';}catch(error){$('#notification-status').textContent=error.message;}};$('#workout-reminders').onchange=savePushPreferences;$('#progression-alerts').onchange=savePushPreferences;
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
restoreDraft().then(loadData).catch(error=>{setConnection('offline','Unavailable');document.querySelector('main').innerHTML=`<div class="empty">Unable to load fitness data: ${escapeHtml(error.message)}</div>`;});
